### ISSUE TITLE
Can't import Tailwind CSS config file

### ISSUE THREAD

**Issue by afuno** [impulse/tailwindcss-figma-plugin#117]
I can't import the default config file: https://raw.githubusercontent.com/tailwindlabs/tailwindcss/master/stubs/defaultConfig.stub.js

**Comment by impulse** [comment]
Directly importing the js config file has been deprecated because it was too ambiguous. See readme for new usage.

**Comment by afuno** [comment]
@impulse I generated the file as written in the README. As a result, the "Add" button is inactive anyway.

<img width="300" alt="Снимок экрана 2020-07-31 в 11 56 12" src="https://user-images.githubusercontent.com/2853419/89018786-06d38e80-d325-11ea-9b17-483496a39c8b.png">

**Comment by impulse** [comment]
Interesting, can you send me the file to troubleshoot it?

**Comment by TheRealNeil** [comment]
I have the same issue.  Is there a solution?
