### ISSUE TITLE
Update to Tailwind 2.0

### ISSUE THREAD

**Issue by helloworld** [impulse/tailwindcss-figma-plugin#122]
It would be really nice if this plugin was updated to use tailwind 2.0

**Comment by impulse** [comment]
@helloworld there should be no breaking changes with v2. Can you elaborate?

**Comment by helloworld** [comment]
Sorry for not adding more detail here!

I believe the main functionality of this plugin is to import the color palette from your tailwind config, and tailwind 2.0 came out with a new color palette: https://blog.tailwindcss.com/tailwindcss-v2. 

So if I paste in my config meant for tailwind 2.0, I won't get the colors I expect and will instead get the v1 colors. 

Also, even though there are limited breaking changes other than colors, there were several new features released so I believe using a config file with tailwind 2.0 specific settings will break the plugin.

**Comment by impulse** [comment]
@helloworld, ah I see. The default values shipped with the plugin still contain the v1 values. However if you use `npx tailwind.json` in your project it will generate an importable file matching your config. The plugin functionality itself shouldn't be breaking for v2.

**Comment by helloworld** [comment]
That makes sense, thanks!

**Comment by helloworld** [comment]
Hey @impulse, I tried what you suggested but unfortunately I'm getting the following error:

![image](https://user-images.githubusercontent.com/3893054/102808668-ab1aa800-438e-11eb-99c0-de8884896100.png)

**Comment by ramiraza** [comment]
I'm experiencing the same problem so I opened an issue for this.

**Comment by impulse** [comment]
@helloworld @ramiraza I just tested and there is no breaking change for v2 in this plugin. I'll change the wording for the upload field since you are not supposed to drag in your tailwind config anymore. You need to run `npx tailwind.json` in your project and import the generated `tailwind.json` file instead (as mentioned above).
