### ISSUE TITLE
Parsing Failed

### ISSUE THREAD

**Issue by ramiraza** [impulse/tailwindcss-figma-plugin#123]
Hey @impulse,

I wanted to point out that your plugin within figma is throwing an exception when tailwind.config.js file is imported into it. It does not however show any problem when the "load default" option is used. I've added a screenshot as a reference. Can you please look at this?

<img width="301" alt="tailwindcss screenshot" src="https://user-images.githubusercontent.com/16007576/103867431-32993400-507c-11eb-99cf-f917ef594d0e.png">

**Comment by impulse** [comment]
https://github.com/impulse/tailwindcss-figma-plugin/issues/122#issuecomment-756773583
