### ISSUE TITLE
[Feature Request] Button for using default config

### ISSUE THREAD

**Issue by adevade** [impulse/tailwindcss-figma-plugin#15]
It would be nice to have a button to load the default config right from Figma.

**Comment by impulse** [comment]
Good idea, will plan on implementing this. For now you can use the [default stub](https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js) or use my Tailwind Figma Kit.

**Comment by impulse** [comment]
Added a load default button and major improvements to the code, sorry it took a while

**Comment by adevade** [comment]
@impulse Don't apologise! Thank you for implementing this feature!
