### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by muhajirdev** [impulse/tailwindcss-figma-plugin#8]
Hi there,
Awesome idea. 
Unfortunately I can't get it to work. On safari, the "add styles". Is not clickable after I upload the file. 

On chrome, after I click "Add styles" nothing happens

**Comment by muhajirdev** [comment]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/12745166/62763113-fcd1d380-bab4-11e9-84e9-e7c0be5887af.png">

Here's what the error saying

**Comment by impulse** [comment]
Hey there 👋🏼,

the plugin communicates with the Figma API, thus it is not possible to use it in an external browser. Please add the `manifest.json` in your Figma Desktop App (Plugins Section).

After that you should see Plugins > Development > Tailwind CSS when right clicking in Figma

![Screenshot 2019-08-09 at 10 08 48](https://user-images.githubusercontent.com/8146736/62764345-f2e8aa00-ba8d-11e9-822b-b3bf078ef6e5.png)

It is quite a hassle to debug / reopen it at the moment.
I hope there will be a solution for a good development workflow in the future.

You can read more about how to interact with the Figma API here:
https://www.figma.com/plugin-docs/creating-ui/
